@startuml
class Program {
    {static} Main(args:string[]) : void
}
class Tärning {
    AntalSidor : int <<get>> <<set>>
    generator : Random
    + Tärning(antalSidor:int)
    + Kasta() : int
}
@enduml
